name: CI

on:
    push: {}
    pull_request: {}

jobs:
    check-cs:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-version: [8.2, 8.3, 8.4]

        steps:
            - name: Checkout code
                uses: actions/checkout@v4

            - name: Set up PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    tools: composer, phpstan, ecs, phpunit
                    coverage: xdebug
                    ini-values: opcache.enable_cli=1

            - name: Get composer cache directory
                id: composer-cache
                run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Cache Composer dependencies
                uses: actions/cache@v4
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php-version }}-composer-

            - name: Cache phpunit
                uses: actions/cache@v4
                with:
                    path: .phpunit.cache
                    key: ${{ runner.os }}-php-${{ matrix.php-version }}-phpunit-${{ hashFiles('**/phpunit.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php-version }}-phpunit-

            - name: Install Composer dependencies
                run: composer install --no-interaction --no-progress --prefer-dist

            - name: Run coding style check
                run: composer ci

            - name: Run unit test
                run: composer coverage
                env:
                    XDEBUG_MODE: coverage

